[package]
name = "Superhero_Tournament"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.9", features = ["lua54"] }
rand = "0.8"

[[bin]]
name = "Superhero_Tournament"
path = "Superhero_Tournament.rs"

